refactor: migrator - extract code into functions
Cleanup generation of environment file.

diff --git a/migrator b/migrator
--- a/migrator
+++ b/migrator
@@ -7,7 +7,7 @@ set -e
 
 shopt -s nullglob
 
-function usage() {
+usage() {
     print "$(cat <<EOF
 $(highlight "up")                                     Start Migrator in background
 $(highlight "down")                                   Stop Migrator
@@ -29,7 +29,7 @@ EOF
 )"
 }
 
-function dependency_barrier {
+dependency_barrier() {
     command -v docker &>/dev/null || \
         error "$(highlight "docker") not installed"
     command -v docker-compose &>/dev/null || \
@@ -38,47 +38,99 @@ function dependency_barrier {
         error "$(highlight "git") not installed"
 }
 
-# Color codes
-RED='\033[1;31m'
-GREEN='\033[1;32m'
-YELLOW='\033[1;33m'
-WHITE='\033[1;37m'
-LIGHT_GREY='\033[1;37m'
-
-# No color
-NC='\033[0m'
-
-function print {
-    printf "${1}\n"
+main() {
+    catch_all_exit_code=1
+    case "${1}" in
+    'up')
+        docker-compose up -d
+        print_url
+        ;;
+    'down')
+        docker-compose down
+        ;;
+    'logs')
+        if [ ! -z "$(docker-compose top)" ]; then
+            docker-compose logs --timestamps --tail='all'
+        else
+            error "Logs not avaliable while not running ($(highlight "'${0} up'") to start)"
+        fi
+        ;;
+    'configure')
+        configure "$@"
+        ;;
+    'update')
+        update "$@"
+        ;;
+    'install')
+        ;&
+    'upgrade')
+        upgrade "$@"
+        ;;
+    'versions')
+        sanctioned_tags
+        ;;
+    'version')
+        if env_file_exists; then
+            print_env 'VERSION'
+        else
+            error "Initial configuration outstanding (run $(highlight "'${0} configure'"))"
+        fi
+        ;;
+    'help')
+        catch_all_exit_code='0'
+        ;&
+    *)
+        usage
+        exit "${catch_all_exit_code}"
+        ;;
+    esac
 }
 
-function highlight {
-    echo "${LIGHT_GREY}${1}${NC}"
+print_url() {
+    ip_addr="$(get_hostname)"
+    if [ ! -z "${ip_addr}" ]; then
+        port=":$(print_env 'EXTERNAL_HTTP_PORT')"
+        if [ "${port}" = ':80' ]; then
+            port=''
+        fi
+
+        ok "Started on $(highlight "'http://${ip_addr}${port}'")"
+    fi
 }
 
-function error {
-    >&2 printf "[${RED}ERROR${NC}] ${1}\n"
-    return ${2-1}
+get_hostname() {
+    # BSD `hostname` doesn't understand the `-I` flag
+    (hostname --all-ip-addresses 2> /dev/null || hostname) | awk '{ print $1 }'
 }
 
-function warn {
-    printf "[${YELLOW}WARN${NC}] ${1}\n"
+print_env() {
+    env -i "${BASH}" -c "set -a; . "${ENV_FILE}"; set +a; echo \${${1}};"
 }
 
-function info {
-    printf "[${WHITE}INFO${NC}] ${1}\n"
+env_file_exists() {
+    [ -f "${ENV_FILE}" ]
 }
 
-function ok {
-    printf "[${GREEN}OK${NC}] ${1}\n"
+configure() {
+    if  generate_environment_file; then
+        next_command="install"
+        installed_from_archive && next_command="${next_command} --archive <archive_file>"
+        info "Run $(highlight "'${0} ${next_command}'") to complete setup"
+    else
+        warn 'Environment file already exists'
+        info "Please modify environment file $(highlight "'${ENV_FILE}'") manually"
+    fi
 }
 
-function generate_environment_file {
+generate_environment_file() {
+    # If file exists return false
+    ! env_file_exists || return
+
+    # File doesn't exist, so generate it
     password="$(generate_random)"
-
     version="$(git describe --exact-match --tags HEAD)"
 
-    cat <<EOF > "${1}"
+    cat <<EOF > "${ENV_FILE}"
 # —— User configurable ——
 EXTERNAL_HTTP_PORT=80
 VERSION=${version}
@@ -87,115 +139,24 @@ VERSION=${version}
 CORE_DB_PASSWORD="${password}"
 EOF
 
-    chmod 600 "${1}"
+    chmod 600 "${ENV_FILE}"
+    ok 'Generated environment file'
 }
 
-function generate_random {
+generate_random() {
     local PASSWORD_CHARSET='A-Za-z0-9!&()*+,-./:;<=>?@{|}~'
     local PASSWORD_LENGTH=32
     LC_ALL=C tr -dc "${PASSWORD_CHARSET}" </dev/urandom | head -c "${PASSWORD_LENGTH}"
 }
 
-# Temporary directory
-TEMP_TEMPLATE='migrator.XXXXXX'
-
-# Directory name in archive
-ARCHIVE_DIR='./cybertec_migrator'
-
-# Environment configuration files
-ENV_FILE='./.env'
-
-# Directory where we save container images provided from offline installation packages
-IMAGE_PATH='images'
-
-# This file exists only if the directory was provided by on offline installation package
-VERSION_FILE='.version'
-
-function most_recent_tag {
-    sanctioned_tags | head -n 1
-}
-
-function sanctioned_tags {
-    git tag --sort=-v:refname
-}
-
-function get_hostname {
-    # BSD `hostname` doesn't understand the `-I` flag
-    (hostname --all-ip-addresses 2> /dev/null || hostname) | awk '{ print $1 }'
-}
-
-# TODO: replace this with sed -I
-function replace_in_place {
-    target=$(mktemp)
-    sed -e "${1}" "${2}" > "${target}"
-    mv "${target}" "${2}"
-}
-
-function version_barrier {
-    if ! git tag | grep -q "^${1}$"; then
-        error "Unknown version $(highlight "${1}")"
-    fi;
-}
-
-function print_url {
-    ip_addr="$(get_hostname)"
-    if [ ! -z "${ip_addr}" ]; then
-        port=":$(print_env 'EXTERNAL_HTTP_PORT')"
-        if [ "${port}" = ':80' ]; then
-            port=''
-        fi;
-
-        ok "Started on $(highlight "'http://${ip_addr}${port}'")"
-    fi;
-}
-
-function print_env {
-    env -i "${BASH}" -c "set -a; . "${ENV_FILE}"; set +a; echo \${${1}};"
-}
-
 # TODO Switch to .meta-inf file which contains more information. For now we
 # remain on the .version file for backwards compatiblity.
-function installed_from_archive() {
+installed_from_archive() {
     [ -f "${VERSION_FILE}" ] && return
     false
 }
 
-dependency_barrier
-
-# Change working directory to directory that contains script
-cd "${0%/*}"
-
-catch_all_exit_code=1
-case "${1}" in
-'up')
-    docker-compose up -d
-    print_url
-    ;;
-'down')
-    docker-compose down
-    ;;
-'logs')
-    if [ ! -z "$(docker-compose top)" ]; then
-        docker-compose logs --timestamps --tail='all'
-    else
-        error "Logs not avaliable while not running ($(highlight "'${0} up'") to start)"
-    fi;
-    ;;
-'configure')
-    if [ ! -f "${ENV_FILE}" ]; then
-        generate_environment_file "${ENV_FILE}"
-
-        ok 'Generated environment file'
-        next_command="install"
-        installed_from_archive && next_command="${next_command} --archive <archive_file>"
-        info "Run $(highlight "'${0} ${next_command}'") to complete setup"
-    else
-        warn 'Environment file already exists'
-        info "Please modify environment file $(highlight "'${ENV_FILE}'") manually"
-    fi;
-
-    ;;
-'update')
+update() {
     # No archive provided → Fetch from origin
     if [ -z "${2}" ]; then
         info 'Updating release information'
@@ -204,9 +165,9 @@ case "${1}" in
         new_version=$(most_recent_tag)
         info "Recommended version: "$(highlight "${new_version}")""
 
-        if [ -f "${ENV_FILE}" ] && [ ! "${new_version}" = $(print_env 'VERSION') ]; then
+        if env_file_exists && [ ! "${new_version}" = $(print_env 'VERSION') ]; then
             info "Run $(highlight "'${0} upgrade'") to upgrade to version ${new_version}"
-        fi;
+        fi
     # Archive provided → Use `.git` folder contained within archive as origin
     elif [ "${2}" = '--archive' ] && [ -f "${3}" ]; then
         info "Updating release information from archive '${3}'"
@@ -220,20 +181,27 @@ case "${1}" in
         git fetch --quiet --tags "${temp_dir}/.git" 1>/dev/null
 
         info "Updated release information"
-        if [ -f "${ENV_FILE}" ] && [ ! "${archive_version}" = $(print_env 'VERSION') ]; then
+        if env_file_exists && [ ! "${archive_version}" = $(print_env 'VERSION') ]; then
             info "Run $(highlight "'${0} upgrade --archive ${3}'") to upgrade to version ${archive_version}"
-        fi;
+        fi
     else
         error "Invalid path $(highlight "${3}")"
-    fi;
-    ;;
-'install')
-    ;&
-'upgrade')
-    # Ensure that the environment file exists
-    if [ ! -f "${ENV_FILE}" ]; then
-        generate_environment_file "${ENV_FILE}"
-    fi;
+    fi
+}
+
+most_recent_tag() {
+    sanctioned_tags | head -n 1
+}
+
+sanctioned_tags() {
+    git tag --sort=-v:refname
+}
+
+upgrade() {
+    # Provide the means to upgrade to a specific version. Needed if we want to
+    # install to an older version than the current one. Especially usefule for
+    # testing.
+    generate_environment_file || true
 
     # No parameters provided → Fetch most recent images from online registry
     if [ -z "${2}" ]; then
@@ -241,7 +209,7 @@ case "${1}" in
 
         if [ -z "${version}" ]; then
             error "No versions available (run $(highlight "'${0} update'") to fetch versions)"
-        fi;
+        fi
 
         info "Pulling images for $(highlight "${version}")"
         if pull_error=$(VERSION="${version}" docker-compose pull 2>&1 > /dev/null); then
@@ -309,22 +277,74 @@ case "${1}" in
 
     info "Run $(highlight "'${0} up'") to switch to new version"
     warn 'Switching will abort running migrations'
-    ;;
-'versions')
-    sanctioned_tags
-    ;;
-'version')
-    if [ -f "${ENV_FILE}" ]; then
-        print_env 'VERSION'
-    else
-        error "Initial configuration outstanding (run $(highlight "'${0} configure'"))"
-    fi;
-    ;;
-'help')
-    catch_all_exit_code='0'
-    ;&
-*)
-    usage
-    exit "${catch_all_exit_code}"
-    ;;
-esac
+}
+
+version_barrier() {
+    if ! git tag | grep -q "^${1}$"; then
+        error "Unknown version $(highlight "${1}")"
+    fi
+}
+
+# TODO: replace this with sed -I
+replace_in_place() {
+    target=$(mktemp)
+    sed -e "${1}" "${2}" > "${target}"
+    mv "${target}" "${2}"
+}
+
+# Color codes
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+WHITE='\033[1;37m'
+LIGHT_GREY='\033[1;37m'
+
+# No color
+NC='\033[0m'
+
+print() {
+    printf "${1}\n"
+}
+
+highlight() {
+    echo "${LIGHT_GREY}${1}${NC}"
+}
+
+error() {
+    >&2 printf "[${RED}ERROR${NC}] ${1}\n"
+    return ${2-1}
+}
+
+warn() {
+    printf "[${YELLOW}WARN${NC}] ${1}\n"
+}
+
+info() {
+    printf "[${WHITE}INFO${NC}] ${1}\n"
+}
+
+ok() {
+    printf "[${GREEN}OK${NC}] ${1}\n"
+}
+
+# Temporary directory
+TEMP_TEMPLATE='migrator.XXXXXX'
+
+# Directory name in archive
+ARCHIVE_DIR='./cybertec_migrator'
+
+# Environment configuration files
+ENV_FILE='./.env'
+
+# Directory where we save container images provided from offline installation packages
+IMAGE_PATH='images'
+
+# This file exists only if the directory was provided by on offline installation package
+VERSION_FILE='.version'
+
+dependency_barrier
+
+# Change working directory to directory that contains script
+cd "${0%/*}"
+
+main "$@"
